[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "pph"
version = "0.0.1"
authors = [{ name = 'Ryan Hamilton', email = "ryan.hamilton@ec.gc.ca" }]
